const homeRoutes = require("./home.route")
const userRoutes = require("./user.route")
const chatRoutes = require("./chat.route")
const usersRoutes = require("./users.route")
const roomsChatRoutes = require("./rooms-chat.route")
const userMiddleware = require("../../middlewares/client/user.middleware")
const authMiddleware = require("../../middlewares/client/auth.middleware")
module.exports = (app) =>{
  app.use(userMiddleware.infoUser)
  app.use("/", homeRoutes)
  app.use("/user", userRoutes)
  app.use("/chat", authMiddleware.auth, chatRoutes)
  app.use("/users", authMiddleware.auth, usersRoutes)
  app.use("/rooms-chat", authMiddleware.auth, roomsChatRoutes)
}